### ISSUE TITLE
Unexpected interference between graphs - node removal

### ISSUE THREAD

**Issue by OleksiyRudenko** [lempiy/react-direct-graph#1]
STR:
1. Navigate to https://lempiy.github.io/react-direct-graph/
2. On **Graph Editing** graph click node **B** -&gt; node **B** disappears and the graph gets re-rendered as expected
3. On **Graph Events** graph click node **C**

Expected effect: none, as **Graph events** graph is not supposed to change on mouse click events

Actual effect: On **Graph Events** node **B** gets moved losing inbound edge from node **A**, node **A** inherits children from node **B**

Before step 3
![image](https://user-images.githubusercontent.com/8686631/59975600-7889c680-95c2-11e9-8fd0-b458fd3bfbff.png)

After step 3
![image](https://user-images.githubusercontent.com/8686631/59975603-88a1a600-95c2-11e9-871e-c1366231b101.png)

Similar effects occur when clicking either of nodes of **Graph Editing** and then on either node of **Graph events**.

**Comment by lempiy** [comment]
Resolved in https://github.com/lempiy/react-direct-graph/commit/b5ecff5d299b9dec3b6cab1bec83a126e2118386
Thx for report
