### ISSUE TITLE
DirectGraph ViewProps export do not include PolyLineViewProps

### ISSUE THREAD

**Issue by madbiker88** [lempiy/react-direct-graph#12]
When trying to recreate the exampleEdit in typescript rather than the provided jsx, I get a typescript error of properties do not exist on DirectGraph whenever using any of the PolyLine ViewProps such as
`onEdgeClick={this.onEdgeClick}
                onEdgeMouseEnter={this.onEdgeMouseEnter}
                onEdgeMouseLeave={this.onEdgeMouseLeave}`
This is because the dist package ViewProps are exported from components/element and not from components/graph.  The graph version is a superset that contains the extra ViewProps for onEdge items but they are not accessible in the dist. version.  

Suggest either enhancing element exports to include polyline ViewProps or better still- add a new GraphViewProps export for the superset of ViewProps that DirectGraph actually uses.

**Comment by lempiy** [comment]
@madbiker88 Thanks for your issue, gonna fix it ASAP.
I have plan to add the possibility to customize graph edges with custom components (in the same way as it's done with nodes) so, probably, I will have to rework graph props in next major tag/release.
