### ISSUE TITLE
General page failure on inter-graph action

### ISSUE THREAD

**Issue by OleksiyRudenko** [lempiy/react-direct-graph#2]
STR:
1. Navigate to https://lempiy.github.io/react-direct-graph/
2. On **Graph editing** graph click either of edges
3. Provide an arbitrary unique `id` to a newly created node -&gt; new node is created as expected
4. Click either of nodes of **Graph events** graph

Expected effect: none

Actual effect: page renders blank, dev console reports `Cannot read property 'id' of undefined`

**Comment by lempiy** [comment]
Resolved in https://github.com/lempiy/react-direct-graph/commit/b5ecff5d299b9dec3b6cab1bec83a126e2118386
thx for report
