### ISSUE TITLE
Shift-Click on demo site has no effect

### ISSUE THREAD

**Issue by OleksiyRudenko** [lempiy/react-direct-graph#4]
STR:
1. Navigate to https://lempiy.github.io/react-direct-graph/
2. On **Graph Editing** Shift-Click either of nodes
3. On **Graph Editing** Shift-Click any different node

Expected effect: an edge binding both nodes is created

Actual effect: none

**Comment by lempiy** [comment]
This is working unless you're clicking on node that will become split/join after adding new edge. This is technical limitation, split-joins will be supported in nearest commits.
Also there's known issue with loop references which is to be resolved too.

**Comment by lempiy** [comment]
#5

**Comment by lempiy** [comment]
@OleksiyRudenko Added backward references(loops) and split joins in v1.1.0
