### ISSUE TITLE
Self reference support. ( Circular dependency)

### ISSUE THREAD

**Issue by prakashsvmx** [lempiy/react-direct-graph#9]
for a given data set 1 <- 1

const graphData = [
      {
        id: "1",
        next: ["2"]
      },
      {
        id: "2",
        next: ["1", "2"]
      },
];

it is not working as expected.

**Comment by lempiy** [comment]
Didn't implement this feature, since don't now the use cases for such data.
Do you expect such graph to be drawn like this:
![Imgur](https://i.imgur.com/vcVLdek.png)

**Comment by prakashsvmx** [comment]
Yes

**Comment by prakashsvmx** [comment]
> Didn't implement this feature, since don't know the use cases for such data.
> Do you expect such graph to be drawn like this: ![Imgur](https://camo.githubusercontent.com/8ba688c66e27a3b0a986f84a74207288e8f8bb32/68747470733a2f2f692e696d6775722e636f6d2f7663564c64656b2e706e67)


https://en.wikipedia.org/wiki/Circular_dependency

**Comment by lempiy** [comment]
Added self reference feature in #10 .
Complex example now includes self reference node.
https://lempiy.github.io/react-direct-graph/
Space optimization - reduction of vertical space occupied by graph in various cases - will be done in future commits.

**Comment by prakashsvmx** [comment]
Thank you very much for accommodating.
